# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Trip Duration API to Azure Web App

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:

env:
  REGISTRY: tripdurationimage.azurecr.io
  IMAGE_NAME: durationcalculate
  APP_NAME: trip-duration-minute

jobs:
  # Continuous Integration
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 06-Azure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Verify files exist
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Checking for requirements.txt:"
          test -f requirements.txt && echo "✓ requirements.txt found" || echo "✗ requirements.txt not found"
          echo "Checking for app.py:"
          test -f app.py && echo "✓ app.py found" || echo "✗ app.py not found"
          echo "Checking for Dockerfile:"
          test -f Dockerfile && echo "✓ Dockerfile found" || echo "✗ Dockerfile not found"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found in 06-Azure directory"
            exit 1
          fi

      - name: Lint code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run unit tests
        run: |
          echo "Running unit tests in $(pwd)"
          # python -m pytest tests/ -v

  # Build and Push Docker Image
  build:
    name: Build and Push Container
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: 06-Azure
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Docker context
        run: |
          echo "Current directory: $(pwd)"
          echo "Files available for Docker build:"
          ls -la
          echo "Checking for Dockerfile:"
          test -f Dockerfile && echo "✓ Dockerfile found" || echo "✗ Dockerfile not found"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push container image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./06-Azure
          file: ./06-Azure/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Generate build summary
        run: |
          echo "### Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Image:** ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags:** ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Digest:** ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY

  # Deploy to Azure Web App
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ needs.build.outputs.image-tag }}

      - name: Verify deployment
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          
          # Get the webapp URL
          WEBAPP_URL="${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          
          # Health check with retry logic
          for i in {1..5}; do
            echo "Health check attempt $i/5..."
            if curl -f -s "$WEBAPP_URL/health" > /dev/null 2>&1; then
              echo "✅ Deployment successful! App is responding."
              exit 0
            elif curl -f -s "$WEBAPP_URL" > /dev/null 2>&1; then
              echo "✅ Deployment successful! App is responding at root."
              exit 0
            else
              echo "⏳ App not ready yet, waiting 30 seconds..."
              sleep 30
            fi
          done
          
          echo "❌ Health check failed after 5 attempts"
          echo "Deployment may have issues. Check Azure portal for details."
          exit 1

      - name: Deployment summary
        if: always()
        run: |
          echo "### Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **App Name:** ${{ env.APP_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** production" >> $GITHUB_STEP_SUMMARY
          echo "- **URL:** ${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image:** ${{ needs.build.outputs.image-tag }}" >> $GITHUB_STEP_SUMMARY

  # Cleanup old images (optional)
  cleanup:
    name: Cleanup Old Images
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: success()
    steps:
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Cleanup old images
        run: |
          echo "Cleaning up old images (keeping last 10)..."
          # This would require Azure CLI or custom script
          echo "Add cleanup logic here if needed"
